apiVersion: v1
kind: Pod
metadata:
        name: nginx-busybox
        labels:
                app: nginx-busybox
                tier: frontend
spec:
        containers:
                - name: nginx
                  image: nginx
                - name: busybox
                  image: busybox
